jobs:
- job: build
  pool:
    name: 'Hosted VS2017'  # name of the pool to run this job in
    demands: 
      - msbuild
      - visualstudio
      - vstest
  steps:
  - checkout: self  
    clean: false
    submodules: recursive  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '>=4.7.1' 
      checkLatest: false # Optional

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      command: 'restore'
      restoreSolution: '*.sln'

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0 
    displayName: 'Component Detection'

  - task: VSBuild@1
    displayName: 'Build Default Configuration'
    inputs:
      solution: '*.sln'
 
